# Generated by Django 5.2.5 on 2025-08-26 14:00

import apps.pages.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('content_type', models.CharField(choices=[('VIDEO', 'Видео'), ('AUDIO', 'Аудио')], max_length=5, verbose_name='Тип контента')),
                ('text', models.TextField(verbose_name='Текст')),
                ('page', apps.pages.models.PageForeignKeyField(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='pages.page')),
            ],
            options={
                'verbose_name': 'Аудиозапись',
                'verbose_name_plural': 'Аудиозаписи',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('content_type', models.CharField(choices=[('VIDEO', 'Видео'), ('AUDIO', 'Аудио')], max_length=5, verbose_name='Тип контента')),
                ('video_url', models.URLField(verbose_name='URL видео')),
                ('subtitles_url', models.URLField(blank=True, default=None, null=True, verbose_name='URL субтитров')),
                ('page', apps.pages.models.PageForeignKeyField(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='pages.page')),
            ],
            options={
                'verbose_name': 'Видеозапись',
                'verbose_name_plural': 'Видеозаписи',
            },
        ),
    ]
