# Generated by Django 5.2.5 on 2025-08-25 08:36

import apps.pages.models
import django.db.models.deletion
from models import mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            bases=(models.Model, mixins.TimestampMixin),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик')),
                ('content_type', models.CharField(choices=[('VIDEO', 'Видео'), ('AUDIO', 'Аудио')], max_length=5, verbose_name='Тип контента')),
                ('text', models.TextField(verbose_name='Текст')),
                ('page', apps.pages.models.PageForeignKeyField(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='pages.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mixins.TimestampMixin),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик')),
                ('content_type', models.CharField(choices=[('VIDEO', 'Видео'), ('AUDIO', 'Аудио')], max_length=5, verbose_name='Тип контента')),
                ('video_url', models.URLField(verbose_name='URL видео')),
                ('subtitles_url', models.URLField(blank=True, default=None, null=True, verbose_name='URL субтитров')),
                ('page', apps.pages.models.PageForeignKeyField(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='pages.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mixins.TimestampMixin),
        ),
    ]
