# Generated by Django 5.2.5 on 2025-08-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='video',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='audio',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров'),
        ),
        migrations.AlterField(
            model_name='video',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров'),
        ),
    ]
