# Generated by Django 5.2.5 on 2025-08-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['page_position', '-created_at'], 'verbose_name': 'Аудиозапись', 'verbose_name_plural': 'Аудиозаписи'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['page_position', '-created_at'], 'verbose_name': 'Видеозапись', 'verbose_name_plural': 'Видеозаписи'},
        ),
        migrations.AddField(
            model_name='audio',
            name='page_position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция на странице'),
        ),
        migrations.AddField(
            model_name='video',
            name='page_position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция на странице'),
        ),
    ]
